### ISSUE TITLE
Using ID

### ISSUE THREAD

**Issue by ecthros** [ecthros/pina-colada#108]
@Kkevsterrr --
I saw you changed the  capabilities/arp/arpSpoof.py file to say "mac address" instead of ID...

As it stands right now, pina colada queries the database for a mac address and IP address based on the given ID of a computer. This means it's a lot easier to use, since "set masq 1" is a lot simpler than saying "set masq_mac aa:bb:cc:dd:ee:ff" and "set masq_ip 127.0.0.1". 

I was at some point going to allow the user to put in their own ip and mac addresses if they so wished as well. However I thought this would be easiest for @jottenwa to implement, since he can just have a drop down menu of all the computers on the network, instead of having to type anything in (the less typing, the better, I think).

**Comment by Kkevsterrr** [comment]
Ohhh my bad I totally misunderstood how the ID worked. Either way, it needs to be implemented at our end, since the front-ends are just going to call into it, so I'll leave it up to you whether you want to leave it as the ID or just type it directly! I personally would prefer giving users the ability to put it in manually or both!

**Comment by ecthros** [comment]
I'm going to leave it as the ID - just a lot simpler to use.

I might give an option to use the IP/MAC address if the user so chooses.
